openapi: "3.0.2"
info:
  title: Härtappat backend API
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1
paths:
  /countries:
    get:
      summary: Get a list of known countries.
      description: Returns a list of known countries in the database. Used to ensure that countries are spelled consistently.
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      summary: Adds one country to the list of known countries
      description: Adds one country to the list of known countries.
      requestBody:
        required: true
        description: One country to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        200:
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'


  /grapes:
    get:
      description: Returns a list of the grapes in the database. Currently the length of the list is unlimited; that may change.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Grape'
    post:
      responses:
        '200':
          description: TODO describe me
    patch:
      responses:
        '200':
          description: TODO describe me
    delete:
      responses:
        '200':
          description: TODO describe me

  /members:
    get:
      description: Returns a list of the members of the club.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    Förnamn:
                      type: string
                      example: Helge
                    Efternamn:
                      type: string
                      example: Stenström
  /tasting:
    get:
      description: Returns a list of all tastings
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tasting'
  /tasting/{id}:
    get:
      description: Returns information about one wine tasting
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tasting'
  /wines:
    get:
      description: Returns a list of the wines in the database. Currently the length of the list is unlimited; that may change.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                      description: The name of the wine, as stated by Systembolaget or by the label.
                    country:
                      type: string
                      description: The name of the country of origin, in Swedish
                    category:
                      type: string
                      description: The currently used categories are 'rött', 'rosé' and 'vitt'.
                    systembolaget:
                      description: The item product number used by Systembolaget.
                      type: integer
    post:
      summary: Adds a wine to the database.
      requestBody:
        description: a wine with properties in textual form
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Wine'
      responses:
        201:
          description: Created


components:
  schemas:
    Grape:
      type: object
      properties:
        name:
          description: The name of the grape.
          type: string
          example: Rondo
        color:
          description: The color of the grape, in Swedish. One of 'grön' or 'blå'.
          type: string
          example: blå
    Member:
      type: object
      properties:
        id:
          type: integer
        Förnamn:
          type: string
          example: Helge
        Efternamn:
          type: string
          example: Stenström
    Tasting:
      type: object
      required:
        - titel
      properties:
        titel:
          type: string
          example: 'Röda viner från Danmark'
        notes:
          type: string
          example: 'Vi provade viner som vi drack i somras. Det var jättetrevligt. Jag skriver mer senare.'
        date:
          type: string
          description: The date the tasting was taking place. In ISO notation.
          example: 2023-01-06
        hosts:
          type: string
          example: Åke och Åsa
    Wine:
      type: object
      properties:
        name:
          type: string
          example: Liebfraumilch
    Country:
      type: string
      example: Österrike
    WineType:
      type: string
