openapi: "3.0.2"
info:
  title: Härtappat backend API
  version: "1.0"
servers:
  - url: http://localhost:3000/api/v1
paths:
  /countries:
    get:
      summary: Get a list of known countries.
      description: Returns a list of known countries in the database. Used to ensure that countries are spelled consistently.
      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryDto'
    post:
      summary: Adds one country to the list of known countries
      description: Adds one country to the list of known countries.
      requestBody:
        required: true
        description: One country to be added
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryCreate'
      responses:
        201:
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDto'
  /countries/{id}:
    get:
      summary: Get one country by id
      description: Returns the country of the given id.
      parameters:
        - name: id
          in: path
          description: ID of the country to get
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDto'

    delete:
      summary: Delete one country by id
      description: Delete one country which is not in use (not registered with any wine). Returns remaining countries.
      parameters:
        - name: id
          in: path
          description: ID of the country to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Successful deletion of the given country
        409:
          description: Cannot delete the country as it is associated with wines.

  /grapes:
    get:
      description: Returns a list of the grapes in the database
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GrapeDto'
    post:
      summary: Create a new grape
      description: Creates a new grape with the provided details
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrapeCreate'
      responses:
        '201':
          description: Grape created successfully.  The response includes the ID of the newly created grape.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrapeDto'

  /grapes/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the grape
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Returns a grape by id
      description: Returns a grape by id, with details
      responses:
        '404':
          description: Grape not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: Successful GET operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrapeDto'
    patch:
      summary: Change a grape identified by id
      description: Change the details of a grape, identified by its id.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GrapeDto'
      responses:
        '404':
          description: Grape not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: Grape changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GrapeDto'
    delete:
      summary: Delete a grape by id
      description: Delete a grape by id
      responses:
        '204':
          description: Grape deleted successfully
        '404':
          description: Grape not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /members:
    get:
      description: Returns a list of the club members.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    given:
                      type: string
                      example: Helge
                    surname:
                      type: string
                      example: Stenström
    post:
      summary: Adds a new member to the club.
      requestBody:
        description: A member with properties in textual form
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemberCreate'
      responses:
        '201':
          description: Member created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Member'

  /tastings:
    get:
      description: Returns a list of all tastings
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TastingDto'

    post:
      summary: Create a new tasting
      description: Adds a new tasting to the database
      requestBody:
        description: A tasting with properties in textual form
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TastingCreate'
      responses:
        201:
          description: Tasting created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TastingDto'

  /tastings/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the tasting
        required: true
        schema:
          type: integer
          format: int64
    get:
      description: Returns information about one wine tasting
      responses:
        200:
          description: Successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TastingDto'
  /wines:
    get:
      description: Returns a list of the wines in the database. Currently, the length of the list is unlimited; that may change.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WineDto'
    post:
      summary: Adds a wine to the database.
      requestBody:
        description: a wine with properties in textual form
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WineCreate'
      responses:
        201:
          description: Created

  /wines/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the wine
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Returns a wine by id
      description: Returns a wine by id, with details
      responses:
        '404':
          description: GET operation failed, wine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '200':
          description: Successful GET operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WineDto'
    delete:
      summary: Deletes a wine from the database
      description: Deletes a wine by its ID, from the database
      responses:
        '404':
          description: Wine not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '204':
          description: Wine deleted successfully

  /wine-types:
    post:
      summary: Create a new wine type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WineTypeCreate'
      responses:
        '201':
          description: Wine type created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WineTypeDto'
    get:
      summary: Get all wine types
      responses:
        '200':
          description: Wine types returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WineTypeDto'

components:
  schemas:
    CountryDto:
      type: object
      required: [id, name, isUsed]
      properties:
        id:
          type: integer
          example: 42
        name:
            type: string
            example: Frankrike
        isUsed:
          type: boolean
          example: true

    CountryCreate:
      type: object
      required: [name]
      properties:
        name:
            type: string
            example: Frankrike

    GrapeDto:
      type: object
      required: [ id, name, color ]
      properties:
        id:
          type: integer
          description: Unique identifier for the grape
        name:
          description: The name of the grape.
          type: string
          example: Rondo
        color:
          $ref: '#/components/schemas/GrapeColor'

    GrapeCreate:
      type: object
      required: [ name, color ]
      properties:
        name:
          type: string
          example: Rondo
        color:
          $ref: '#/components/schemas/GrapeColor'

    Member:
      type: object
      required: [id, given, surname]
      properties:
        id:
          type: integer
        given:
          type: string
          example: Helge
        surname:
          type: string
          example: Stenström

    MemberCreate:
      type: object
      required: [given, surname]
      properties:
        given:
          type: string
          example: Helge
        surname:
          type: string
          example: Stenström

    TastingDto:
      type: object
      required: [ id, title ]
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: 'Röda viner från Danmark'
        notes:
          type: string
          example: 'Vi provade viner som vi drack i somras. Det var jättetrevligt. Jag skriver mer senare.'
        date:
          type: string
          format: date
          description: The date the tasting was taking place. In ISO notation.
          example: 2023-01-06

    TastingCreate:
      type: object
      required: [ title, date ]
      properties:
        title:
          type: string
          example: 'Röda viner från Danmark'
        notes:
          type: string
          example: 'Vi provade viner som vi drack i somras. Det var jättetrevligt. Jag skriver mer senare.'
        date:
          type: string
          description: The date the tasting was taking place. In ISO notation.
          example: 2023-01-06

    WineDto:
      type: object
      required: [id, name, country, wineType]
      properties:
        id:
          type: integer
          example: 42
        name:
          type: string
          example: Liebfraumilch
        systembolaget:
          type: number
        volume:
          type: number

        vintageYear:
          type: integer
          nullable: true
          example: 2019

        isNonVintage:
          type: boolean
          example: false

        country:
          $ref: '#/components/schemas/CountryDto'
        wineType:
          $ref: '#/components/schemas/WineTypeDto'


    WineCreate:
      type: object
      required: [ name, countryId, wineTypeId ]
      properties:
        name:
          type: string
          example: Liebfraumilch
        countryId:
          type: integer
          example: 7
        wineTypeId:
          type: integer
          example: 2

    WineTypeDto:
      type: object
      required: [id, name, isUsed]
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Vitt
        isUsed:
          type: boolean
          example: true

    WineTypeCreate:
      type: object
      required: [name]
      properties:
        name:
          type: string
          example: Rött


    GrapeColor:
      description: The color of the grape, in Swedish.
      type: string
      enum: [ blå, grön, annan, okänd ]

    ErrorResponse:
      type: object
      required: [status, message]
      properties:
        status:
          type: integer
          example: 404
        message:
          type: string
          example: Wine not found