@baseUrl = http://localhost:3000/api/v1

### Get all countries
GET  {{baseUrl}}/countries
Accept: application/json

### Post a country
POST {{baseUrl}}/countries
Content-Type: application/json

{
  "name": "Iran"
}

